### ISSUE TITLE
Missing obfuscated sample jar.

### ISSUE THREAD

**Issue by Trol1337** [SerenityEnterprises/paramorphism-issues#4]
The example "FizzBuzz" doesn't have an sample jar which was obfuscated using the Paramorphism obfuscator.

**Comment by half-cambodian-hacker-man** [comment]
The issue tracker examples will not contain any JAR files. To build the fizzbuzz project, please navigate to the fizzbuzz directory, execute `gradle build`, go to the parent directory, and run paramorphism.

Since paramorphism is deterministic, the class files contained within the JAR file should be byte-for-byte equal upon each run.
